language: node_js
node_js: '8'
cache: npm
before_script: npm install
script:
- npm run build
- cp -t . game/index.html game/jump-n-bump.js
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages
notifications:
  email:
    on_success: never